Repository ValueWith/ValueWith_FE, pull requests merged in 2023-11, with the labels that each got.

#6 Drag and drop
  package-lock.json
  package.json
  src/components/group/recruit/GroupItemCard/index.tsx
  src/components/group/recruit/GroupRegistSchedule/index.tsx
  src/main.tsx
Labels: ✨ Feature

#9 Fix : 공통 컴포넌트를 시안과 동일하게 보이도록 수정
  src/assets/styles/GlobalStyles.tsx
Labels: 🎨 Design, 🐞 BugFix

#10 Design : Group 페이지 및 TripCard 디자인 수정
  src/components/GroupFilter/GroupFilter.styles.ts
  src/components/GroupFilter/index.tsx
  src/components/GroupTripList/GroupTripList.styles.ts
  src/components/GroupTripList/index.tsx
  src/components/GroupUserInfo/index.tsx
  src/components/TripCard/TripCard.styles.ts
  src/pages/group/GroupMain/index.tsx
Labels: 🎨 Design

#14 Design : UserInfo 영역이 언제나 카드 가장 하단에 위치하도록 수정
  src/components/GroupUserInfo/GroupUserInfo.styles.ts
  src/components/TripCard/TripCard.styles.ts
  src/components/TripCard/index.tsx
Labels: 🎨 Design

#18 Feat: 그룹 상세 페이지 UI
  db.json
  src/Router.tsx
  src/apis/groupDetail.ts
  src/components/GroupUserInfo/index.tsx
  src/components/TripList/index.tsx
  src/components/group/detail/GroupMemberStatus/GroupMemberStatus.styles.ts
  src/components/group/detail/GroupMemberStatus/index.tsx
  src/components/group/detail/GroupTitle/GroupTitle.styles.ts
  src/components/group/detail/GroupTitle/index.tsx
  src/components/group/detail/TripPlaceCard/TripPlaceCard.styles.ts
  src/components/group/detail/TripPlaceCard/index.tsx
  src/components/group/detail/TripPlaceList/TripPlaceList.styles.ts
  src/components/group/detail/TripPlaceList/index.tsx
  src/components/group/detail/TripTitle/TripTitle.styles.ts
  src/components/group/detail/TripTitle/index.tsx
  src/hooks/useGroup.tsx
  src/pages/Home/index.tsx
  src/pages/group/GroupDetail/GroupDetail.styles.ts
  src/pages/group/GroupDetail/index.tsx
  src/utils/dateUtil.ts
Labels: ✨ Feature

#20 Design: 그룹 상세 페이지 스타일 수정
  src/components/TripCard/index.tsx
  src/components/TripCardUserInfo/TripCardUserInfo.styles.ts
  src/components/TripCardUserInfo/index.tsx
  src/components/group/detail/GroupMemberStatus/GroupMemberStatus.styles.ts
  src/components/group/detail/GroupMemberStatus/index.tsx
  src/components/group/detail/TripPlaceCard/TripPlaceCard.styles.ts
Labels: 🎨 Design

#22 Feat : 회원가입 & 로그인 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/apis/user.model.ts
  src/apis/user.ts
  src/components/Button/Button.styles.ts
  src/components/Header/index.tsx
  src/components/Loader/index.tsx
  src/components/Message/ErrorMessage/index.tsx
  src/components/modal/Alert/index.tsx
  src/components/modal/Confirm/index.tsx
  src/components/modal/model.ts
  src/components/modal/styles.ts
  src/hooks/useAuth.tsx
  src/hooks/useEmailValidation.tsx
  src/pages/user/Login/index.tsx
  src/pages/user/Signup/index.tsx
  src/recoil/modalState.ts
  src/recoil/userState.ts
  src/utils/extractNumber.ts
  src/utils/fetchAction.ts
Labels: 🔨 Refactor, ✨ Feature

#19 Feat: 채팅 페이지 UI
  db.json
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/chat.ts
  src/components/chat/ChatRoomCard/ChatRoomCard.styles.ts
  src/components/chat/ChatRoomCard/index.tsx
  src/components/chat/ChatRoomList/ChatRoomList.styles.ts
  src/components/chat/ChatRoomList/index.tsx
  src/components/chat/RoomMessageCard/RoomMessageCard.styles.ts
  src/components/chat/RoomMessageCard/index.tsx
  src/components/chat/RoomMessageList/RoomMessageList.styles.ts
  src/components/chat/RoomMessageList/index.tsx
  src/hooks/useChat.tsx
  src/pages/chat/Chat.styles.ts
  src/pages/chat/index.tsx
  src/recoil/chatRoomIdState.ts
Labels: ✨ Feature

#23 Refactor: 그룹 페이지 UI 수정
  src/components/Header/index.tsx
  src/components/HomeTripList/index.tsx
  src/components/TripList/TripList.styles.ts
  src/components/group/list/GroupTripList/GroupTripList.styles.ts
  src/components/template/MainTemplate.tsx/MainTemplate.styles.ts
  src/pages/group/GroupMain/GroupMain.styles.ts
  src/pages/group/GroupMain/index.tsx
Labels: 🔨 Refactor, 🎨 Design

#25 Fix : 로그인 토큰을 recoil-persist에서 웹 스토리지로 관리
  src/apis/index.ts
  src/components/Header/index.tsx
  src/hooks/useAuth.tsx
  src/recoil/userState.ts
Labels: 🐞 BugFix

#26 Refactor: 그룹 페이지 전반적으로 수정
  src/components/Header/index.tsx
  src/components/SearchBar/index.tsx
  src/components/TripCard/TripCard.styles.ts
  src/components/TripList/TripList.styles.ts
  src/components/TripList/index.tsx
  src/components/group/list/GroupFilter/index.tsx
  src/components/group/list/GroupTripList/index.tsx
  src/pages/group/GroupMain/index.tsx
  src/utils/conversionArea.ts
  src/utils/conversionGender.ts
  src/utils/dateUtil.ts
Labels: 🐞 BugFix

#29 Feat : 토큰 만료시 자동 로그인 연장
  src/apis/index.ts
  src/apis/user.ts
  src/components/Header/Header.styles.ts
  src/components/Header/index.tsx
  src/hooks/useAuth.tsx
Labels: 🔨 Refactor, ✨ Feature

#30 Refactor : 마지막 카드에서는 하단 줄 뜨지 않도록 수정, distance가 null일때는 화살표 감춤 처리
  src/components/group/detail/TripPlaceCard/index.tsx
  src/components/group/detail/TripPlaceList/index.tsx
Labels: 🎨 Design

#28 Feat : 그룹 모집 기능 구현
  src/apis/regist.ts
  src/components/DateInput/DateInput.styles.ts
  src/components/DateInput/index.tsx
  src/components/group/recruit/GroupItemCard/index.tsx
  src/components/group/recruit/GroupNavSidebar/index.tsx
  src/components/group/recruit/GroupRegistInfo/index.tsx
  src/components/group/recruit/GroupRegistSchedule/index.tsx
  src/components/group/recruit/KakaoMap/index.tsx
  src/components/group/recruit/NestedSidebar/index.tsx
  src/components/modal/model.ts
  src/components/uploader/FileUploader/index.tsx
  src/components/uploader/Uploader.styles.ts
  src/hooks/useMapSearch.tsx
  src/hooks/useRegist.tsx
  src/hooks/useRegistFormValidation.tsx
  src/pages/group/GroupRecruit/index.tsx
  src/pages/user/Login/index.tsx
  src/recoil/GroupRegistState.ts
  src/recoil/modalState.ts
  src/utils/conversionArea.ts
  src/utils/dateUtil.ts
  src/utils/findCodeByLabel.ts
  src/utils/getMarkerBackground.ts
Labels: ✨ Feature, 📬 API

#34 Feat : 그룹 상세 페이지 지도 추가
  src/components/group/detail/TripPlaceCard/index.tsx
  src/components/group/recruit/GroupNavSidebar/index.tsx
  src/components/group/recruit/KakaoMap/index.tsx
  src/pages/group/GroupDetail/index.tsx
  src/pages/group/GroupRecruit/index.tsx
  src/recoil/GroupRegistState.ts
Labels: 🔨 Refactor, ✨ Feature

#35 Feat : 에러 페이지 생성
  src/Router.tsx
  src/assets/Error.svg
  src/pages/user/Error/index.tsx
Labels: 🎨 Design, ✨ Feature

#36 Refactor : Header에 유저 정보 보여주도록 수정
  src/components/DropdownMenu/index.tsx
  src/components/Header/Header.styles.ts
  src/components/Header/index.tsx
Labels: 🔨 Refactor, 🎨 Design

#37 Feat : 그룹 상세 페이지
  src/apis/group.ts
  src/apis/groupApply.ts
  src/apis/groupDetail.ts
  src/components/TripCardUserInfo/TripCardUserInfo.styles.ts
  src/components/group/detail/ApplyButton/index.tsx
  src/components/group/detail/GroupMemberStatus/GroupMemberStatus.styles.ts
  src/components/group/detail/GroupMemberStatus/index.tsx
  src/components/group/detail/TripPlaceCard/TripPlaceCard.styles.ts
  src/components/group/detail/TripPlaceCard/index.tsx
  src/components/group/detail/TripPlaceList/TripPlaceList.styles.ts
  src/components/group/detail/TripPlaceList/index.tsx
  src/components/group/detail/TripTitle/TripTitle.styles.ts
  src/components/group/detail/TripTitle/index.tsx
  src/components/group/list/GroupFilter/GroupFilter.styles.ts
  src/components/group/list/GroupFilter/index.tsx
  src/components/group/recruit/GroupNavSidebar/index.tsx
  src/components/group/recruit/KakaoMap/index.tsx
  src/hooks/useGroup.tsx
  src/pages/group/GroupDetail/GroupDetail.styles.ts
  src/pages/group/GroupDetail/index.tsx
  src/pages/group/GroupMain/index.tsx
  src/pages/group/GroupRecruit/index.tsx
  src/recoil/GroupRegistState.ts
  src/utils/checkApplicationStatus.ts
  src/utils/metersToKilometers.ts
Labels: ✨ Feature

#38 Fix : 회원가입 페이지 파일 있을 때만 파일 압축 진행 & 모달 리팩토링
  src/hooks/useAuth.tsx
  src/pages/user/Signup/index.tsx
  src/utils/fetchAction.ts
Labels: 🔨 Refactor

#39 Fix : 그룹모집 폼 제출 시 날짜 포맷 변경
  src/utils/dateUtil.ts
Labels: 🐞 BugFix

#42 Refactor : 로그인 확인 여부, 유저 정보 확인하는 로직을 커스텀 훅으로 분리
  src/components/Header/index.tsx
  src/hooks/useUser.tsx
  src/pages/group/GroupDetail/index.tsx
Labels: 🔨 Refactor

#40 Fix : status가 approved인 그룹 멤버만 상세 페이지에 보이도록 수정
  src/components/Header/index.tsx
  src/components/group/detail/GroupMemberStatus/index.tsx
Labels: 🔨 Refactor

#43 Feat : 그룹 수정 페이지 추가
  src/App.tsx
  src/Router.tsx
  src/apis/regist.ts
  src/components/group/recruit/GroupNavSidebar/index.tsx
  src/components/group/recruit/GroupRegistInfo/index.tsx
  src/components/uploader/FileUploader/index.tsx
  src/hooks/useRegist.tsx
  src/pages/group/GroupEdit/index.tsx
Labels: 🔨 Refactor, ✨ Feature

#44 Feat : 누락된 드롭다운 메뉴 & 수정 메뉴 기능 추가
  src/components/Header/index.tsx
  src/hooks/useGroup.tsx
Labels: 🎨 Design

#45 Feat : 내 프로필 수정
  src/Router.tsx
  src/apis/mylounge.ts
  src/components/Header/index.tsx
  src/components/uploader/ProfileUploader/index.tsx
  src/hooks/useFileUploader.tsx
  src/hooks/useLounge.tsx
  src/hooks/useUser.tsx
  src/pages/mylounge/EditProfile/index.tsx
Labels: ✨ Feature

#47 Chore : 빌드 오류 대응 및 QA
  .gitignore
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/group.ts
  src/apis/groupApply.ts
  src/apis/groupDetail.ts
  src/apis/index.ts
  src/apis/mylounge.ts
  src/apis/regist.ts
  src/apis/user.ts
  src/components/Header/index.tsx
  src/components/HomeTripList/index.tsx
  src/components/TripList/index.tsx
  src/components/group/detail/ApplyButton/index.tsx
  src/components/group/detail/TripPlaceCard/index.tsx
  src/components/group/recruit/GroupRegistSchedule/index.tsx
  src/components/group/recruit/KakaoMap/index.tsx
  src/components/group/recruit/NestedSidebar/NestedSidebar.styles.ts
  src/components/group/recruit/NestedSidebar/index.tsx
  src/hooks/useRegist.tsx
  src/pages/Home/Home.styles.ts
  src/pages/Home/index.tsx
  src/pages/group/GroupDetail/index.tsx
  src/pages/group/GroupMain/index.tsx
  src/pages/mylounge/GroupManagement/index.tsx
  src/pages/user/Error/index.tsx
  src/pages/user/Signup/index.tsx
  src/recoil/GroupRegistState.ts
  src/recoil/paramsState.ts
Labels: 🔨 Refactor, 🐞 BugFix

#48 Chore : 메인 페이지
  src/components/HomeTripList/index.tsx
Labels: 🐞 BugFix

#49 File : 폴더 트리 구조 변경
  src/App.tsx
  src/components/GroupMemberManagement/index.tsx
  src/components/GroupUserInfo/index.tsx
  src/components/chat/RoomMessageList/index.tsx
  src/components/common/Button/Button.styles.ts
  src/components/common/Button/index.tsx
  src/components/common/DateInput/DateInput.styles.ts
  src/components/common/DateInput/index.tsx
  src/components/common/Dropdown/Dropdown.styles.ts
  src/components/common/Dropdown/index.tsx
  src/components/common/DropdownMenu/DropdownMenu.styles.ts
  src/components/common/DropdownMenu/index.tsx
  src/components/common/Footer/Footer.styles.ts
  src/components/common/Footer/index.tsx
  src/components/common/Header/Header.styles.ts
  src/components/common/Header/index.tsx
  src/components/common/Input/Input.styles.ts
  src/components/common/Input/index.tsx
  src/components/common/Loader/Loader.styles.ts
  src/components/common/Loader/index.tsx
  src/components/common/Message/ErrorMessage/ErrorMessage.styles.tsx
  src/components/common/Message/ErrorMessage/index.tsx
  src/components/common/Pagination/Pagination.styles.tsx
  src/components/common/Pagination/index.tsx
  src/components/common/RadioGroup/Radio.styles.ts
  src/components/common/RadioGroup/index.tsx
  src/components/common/SearchBar/SearchBar.styles.ts
  src/components/common/SearchBar/index.tsx
  src/components/common/SkeletonImage/index.tsx
  src/components/common/uploader/FileUploader/index.tsx
  src/components/common/uploader/ProfileUploader/index.tsx
  src/components/common/uploader/Uploader.styles.ts
  src/components/group/card/TripCard/TripCard.styles.ts
  src/components/group/card/TripCard/index.tsx
  src/components/group/card/TripCardUserInfo/TripCardUserInfo.styles.ts
  src/components/group/card/TripCardUserInfo/index.tsx
  src/components/group/card/TripList/TripList.styles.ts
  src/components/group/card/TripList/index.tsx
  src/components/group/detail/ApplyButton/index.tsx
  src/components/group/detail/GroupMemberStatus/index.tsx
  src/components/group/list/GroupFilter/index.tsx
  src/components/group/list/GroupSearch/index.tsx
  src/components/group/list/GroupTripList/index.tsx
  src/components/group/recruit/GroupItemCard/index.tsx
  src/components/group/recruit/GroupRegistInfo/index.tsx
  src/components/group/recruit/GroupRegistSchedule/index.tsx
  src/components/group/recruit/KakaoMap/index.tsx
  src/components/group/recruit/NestedSidebar/index.tsx
  src/components/home/HomeTripList/index.tsx
  src/pages/Home/index.tsx
  src/pages/group/GroupDetail/index.tsx
  src/pages/group/GroupMain/index.tsx
  src/pages/mylounge/EditProfile/index.tsx
  src/pages/mylounge/GroupManagement/index.tsx
  src/pages/user/Error/index.tsx
  src/pages/user/Login/index.tsx
  src/pages/user/Signup/index.tsx
Labels: 🔨 Refactor

#51 Refactor: 그룹 상세 페이지 전반적인 수정
  src/apis/group.ts
  src/apis/groupApply.ts
  src/apis/groupDetail.ts
  src/components/group/detail/ApplyButton/index.tsx
  src/components/group/detail/GroupMemberStatus/GroupMemberStatus.styles.ts
  src/components/group/detail/GroupMemberStatus/index.tsx
  src/components/group/detail/GroupTitle/GroupTitle.styles.ts
  src/components/group/detail/GroupTitle/index.tsx
  src/components/group/detail/TripPlaceCard/index.tsx
  src/components/group/detail/TripPlaceList/index.tsx
  src/constants/groupModalOption.ts
  src/hooks/useGroup.tsx
  src/hooks/useRegist.tsx
  src/pages/group/GroupDetail/index.tsx
  src/utils/checkApplicationStatus.ts
Labels: 🔨 Refactor

#52 Fix : 그룹 모집 페이지 & 상세 페이지 & 수정 페이지 오류 수정 및 디테일 추가
  src/components/common/DateInput/index.tsx
  src/components/common/SearchBar/index.tsx
  src/components/group/recruit/GroupRegistInfo/index.tsx
  src/components/group/recruit/KakaoMap/index.tsx
  src/hooks/useGroup.tsx
  src/hooks/useRegist.tsx
  src/pages/group/GroupDetail/index.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#53 Design : 그룹 모집 페이지 UX 개선
  src/components/common/Button/Button.styles.ts
  src/components/common/Button/index.tsx
  src/components/common/Input/Input.styles.ts
  src/components/group/recruit/GroupItemCard/index.tsx
Labels: 🎨 Design
